:root = http://localhost:6868
:ekg = http://localhost:8000
#
POST :root/handlers
Content-Type: application/json
{ "codename" : "" }
#
POST :root/handlers
Content-Type: application/json
{}
#
GET :root/docs
#
POST :root/hitman
Content-Type: application/json
{ "codename" : "fewew"}
# FIXME User Valiation? so that what was missing wil be clear
POST :root/signup
Content-Type: application/json
{ "new_password" : "34", "confirm_password": "34", "user_name": "Hans", "payload": {"codename": "EX"}}
# { "new_password" : "1T34a320j", "confirm_password": "1T34a320j", "user_name": "Hans", "payload": {"codename": "EX"}}
#
POST :root/login
Content-Type: application/json
{ "password" : "1T34a320j", "login": "Hans"}
#
POST :root/hitman
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXQiOnsiY29kZW5hbWUiOiJFWCIsImRpZV9hdCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjEtMDEtMDMgMTQ6NDI6MTQuMTQwNDA5IiwiaGFuZGxlcl9pZCI6Mn19.DOIhBVLbC7jITeuzF1m8G3LzPzwa1FzyjW2zT3udmLDqDpI2cv63b2rgzQ3WaDXBuxgmnGWr8uM0Zr2rhgH3jQ
Content-Type: application/json
{ "codename" : "" }
#
GET :root/hitman
#
DELETE :root/hitman/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXQiOnsiY29kZW5hbWUiOiJFWCIsImRpZV9hdCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjEtMDEtMDMgMTQ6NDI6MTQuMTQwNDA5IiwiaGFuZGxlcl9pZCI6Mn19.DOIhBVLbC7jITeuzF1m8G3LzPzwa1FzyjW2zT3udmLDqDpI2cv63b2rgzQ3WaDXBuxgmnGWr8uM0Zr2rhgH3jQ
#
GET :ekg
Accept: application/json
