#
POST http://localhost:6868/handlers
Content-Type: application/json
{}
#
{"codename":"testing","die_at":null}
#
GET http://localhost:6868/docs
#
POST http://localhost:6868/hitman
Content-Type: application/json
{ "codename" : "fewew"}
