name: "Backend Build"
on:
  - pull_request
  - push:
      paths:
        - 'backend/**'
        # - 'nix/**'
        - 'project.materialized'
        # - 'servant-with-beam.cabal'
jobs:
    backend:
        name: backend /  ${{matrix.release}} / ghc ${{matrix.ghc}}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                ghc: [865, 884, 8104]
                sedArg: ["", "''"]
                release: ["linux", "osx", "windows", "static"]
                exclude:
                  - os: ubuntu-latest
                    sedArg: "''"
                  - os: macos-latest
                    sedArg: ""
                    # no osx on ubuntu
                  - os: ubuntu-latest
                    release: "osx"
                    # only osx on macos
                  - os: macos-latest
                    release: "linux"
                  - os: macos-latest
                    release: "static"
                  - os: macos-latest
                    release: "windows"
                    # static don't work
                  - release: "static"
                    ghc: 865
                  - release: "static"
                    ghc: 884
                  - release: "static"
                    ghc: 8104
                    # no 8102 for osx and linux
                  - release: "windows"
                    ghc: 865
                  - release: "windows"
                    ghc: 884
                # include:
                  # - release: "static"
                  #   cache: "static-haskell-nix"

        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
              # with:
              #   install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
              #   extra_nix_config: |
              #     experimental-features = nix-command flakes
              #
            - uses: cachix/cachix-action@v8
              with:
                  name: servant-with-beam
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
                  # extraPullNames: ${{ matrix.cache }}
            - name: add haskell.nix pub keys, add haskell.nix substituters
              run: |
                sed -i ${{matrix.sedArg}} '/^trusted-public-keys =/ s/$/ hydra.iohk.io:f\/Ea+s+dFdN+3Y\/G+FDgSq+a5NEWhJGzdjvKNGv0\/EQ=/' ~/.config/nix/nix.conf
                sed -i ${{matrix.sedArg}} '/^substituters =/ s/$/ https:\/\/hydra.iohk.io/' ~/.config/nix/nix.conf
            - name: nix-build
              run: nix-build -j4 --argstr compiler ghc${{matrix.ghc}} --arg default false -A servant-with-beam.${{matrix.release}}
            - name: nix-shell
              if: matrix.release == 'osx' && matrix.ghc == '8104'
              working-directory: ./backend
              run: nix-shell -j4

# FIXME dependencies text-icu can't build on windows and fuck this up
# NOTEhttps://github.com/hasufell/stack2cabal/blob/master/.github/workflows/release.yaml
# NOTE https://kodimensional.dev/github-actions
