name: "Nix Build"
on:
    [ pull_request, push ]
jobs:
    frontend-phone:
        name: frontend / ${{matrix.release}} / ${{matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                sedArg: ["", "''"]
                release: ["ios", "android", "ghc", "ghcjs"]
                exclude:
                  - os: ubuntu-latest
                    sedArg: "''"
                  - os: macos-latest
                    sedArg: ""
                  - os: ubuntu-latest
                    release: "ios"
                  - os: macos-latest
                    release: "android"

        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: servant-with-beam
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            - name: add haskell.nix pub keys, add haskell.nix substituters
              run: |
                sed -i ${{matrix.sedArg}} '/^trusted-public-keys =/ s/$/ ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI=/' ~/.config/nix/nix.conf
                sed -i ${{matrix.sedArg}} '/^substituters =/ s/$/ https:\/\/nixcache.reflex-frp.org/' ~/.config/nix/nix.conf
            - name: nix-build
              run: nix-build -j4 -A ${{matrix.release}}.frontend
            - name: nix-shell
              if: matrix.release == 'ghc' && matrix.os == 'macos-latest'
              working-directory: ./frontend
              run: nix-shell -j4
