name: "Deploy"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        # with:
        #   install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        #   extra_nix_config: |
        #     experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
            name: servant-with-beam
            authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: add haskell.nix pub keys
        run: sed -i '/^trusted-public-keys =/ s/$/ hydra.iohk.io:f\/Ea+s+dFdN+3Y\/G+FDgSq+a5NEWhJGzdjvKNGv0\/EQ=/' ~/.config/nix/nix.conf
      - name: add haskell.nix substituters
        run: sed -i '/^substituters =/ s/$/ https:\/\/hydra.iohk.io/' ~/.config/nix/nix.conf
      - name: build with nix
        run: nix-build -A servant-with-beam.components.exes.app
      # - name: commit
      #   run: git config user.name "deploy-bot" && git config user.email "deploy-bot-no-reply@github.com" && git add -A && git commit -m "build result commit"
      - uses: akhileshns/heroku-deploy@v3.9.9
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        with:
          heroku_api_key: "${{ secrets.HEROKU_API_KEY }}"
          heroku_app_name: "servant-with-beam"
          heroku_email: "jackychany321@gmail.com"
          dontuseforce: "false"
          appdir: "result/bin"
          # justlogin: true
      # - run: heroku auth:whoami
