name: "Frontend Build"
on:
  pull_request:
  push:
    paths:
      - 'frontend/**'
      # - 'nix/**'
      - 'project.frontend.materialized'
      - '.github/workflows/frontend.yml'
      # - 'servant-with-beam.cabal'
jobs:
    frontend:
        name: frontend/${{matrix.release}}/ghc${{matrix.ghc}}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                ghc: [865, 884, 8104]
                sedArg: ["", "''"]
                release: ["linux", "osx", "windows"]
                exclude:
                  - os: ubuntu-latest
                    sedArg: "''"
                  - os: macos-latest
                    sedArg: ""
                    # no osx on ubuntu
                  - os: ubuntu-latest
                    release: "osx"
                    # only osx on macos
                  - os: macos-latest
                    release: "linux"
                  - os: macos-latest
                    release: "windows"

        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: servant-with-beam
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            - name: add haskell.nix pub keys, add haskell.nix substituters
              run: |
                sed -i ${{matrix.sedArg}} '/^trusted-public-keys =/ s/$/ hydra.iohk.io:f\/Ea+s+dFdN+3Y\/G+FDgSq+a5NEWhJGzdjvKNGv0\/EQ=/' ~/.config/nix/nix.conf
                sed -i ${{matrix.sedArg}} '/^substituters =/ s/$/ https:\/\/hydra.iohk.io/' ~/.config/nix/nix.conf
            - name: nix-build
              run: nix-build -j4 --argstr compiler ghc${{matrix.ghc}} --arg default false --arg js true -A servant-with-beam.${{matrix.release}}
            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: frontend-${{matrix.release}}-ghc${{matrix.ghc}}
                path: result*/**/*
            - name: nix-shell
              if: matrix.release == 'osx' && matrix.ghc == '865'
              working-directory: ./frontend
              run: nix-shell -j4

    frontend:
        name: frontend/${{matrix.release}}/ghc${{matrix.ghc}}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                ghc: [865, 884, 8104]
                sedArg: ["", "''"]
                release: ["linux", "osx", "windows", "iphone", "android"]
                exclude:
                  - os: ubuntu-latest
                    sedArg: "''"
                  - os: macos-latest
                    sedArg: ""
                    # no osx on ubuntu
                  - os: ubuntu-latest
                    release: "iphone"
                    # only osx on macos
                  - os: macos-latest
                    release: "android"

        runs-on: ${{matrix.os}}
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: servant-with-beam
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            - name: add haskell.nix pub keys, add haskell.nix substituters
              run: |
                sed -i ${{matrix.sedArg}} '/^trusted-public-keys =/ s/$/ hydra.iohk.io:f\/Ea+s+dFdN+3Y\/G+FDgSq+a5NEWhJGzdjvKNGv0\/EQ=/' ~/.config/nix/nix.conf
                sed -i ${{matrix.sedArg}} '/^substituters =/ s/$/ https:\/\/hydra.iohk.io/' ~/.config/nix/nix.conf
            - name: nix-build
              run: nix-build -j4 --argstr compiler ghc${{matrix.ghc}} --arg default false --arg frontend true -A servant-with-beam.${{matrix.release}}
            - name: upload artifact
              uses: actions/upload-artifact@v2
              with:
                name: frontend-${{matrix.release}}-ghc${{matrix.ghc}}
                path: result*/**/*
