name: "Nix Build"
on:
    [ pull_request ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: fanshi1028
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
            - name: add haskell.nix pub keys
              run: sed -i '/^trusted-public-keys =/ s/$/ hydra.iohk.io:f\/Ea+s+dFdN+3Y\/G+FDgSq+a5NEWhJGzdjvKNGv0\/EQ=/' ~/.config/nix/nix.conf
            - name: add haskell.nix substituters
              run: sed -i '/^substituters =/ s/$/ https:\/\/hydra.iohk.io/' ~/.config/nix/nix.conf
            - run: nix-build -A servantWithBeam.components.exes.app
            - uses: actions/upload-artifact@v2
              with:
                  name: servant-with-beam
                  path: result/bin/app
            - run: echo ok
